### PR TITLE
Update README screenshot to the new URL

### PR DESCRIPTION
**Pull request by allejo**
Sorry for disregarding your PR template, hope a quick little README change doesn't require a new issue to be created 😅

### CODE REVIEW

**Comment by 255kb** [comment]
@allejo No problem for such a small change :) 
Thank you for catching this I was sure I changed the URLs everywhere...

**Comment by 255kb** [comment]
One thing, coud you please instead of starting from `open-api` branch start from master and ask for a merge into master? 
I am not sure when the `open-api` branch will be ready. Probably not before some months.
Thank you

**Comment by allejo** [comment]
Oops! Didn't realize I was on the `open-api` branch when I made that change; should be fixed now.

**Comment by 255kb** [comment]
Thank you!

**Pull request merged**
