### PR TITLE
Added ability to disable routes, view proxy responses, and create routes from proxy responses.

### PR DESCRIPTION
**Pull request by SaswatB**

### CODE REVIEW

**Comment by gliubc** [comment]
i like the ablity you added, but i am a newbie on electron, and don't know how to build an app from the repo, could you send me an macOS app with the ability you added. My gmail: liubaocheng999@gmail.com .  Thank you very much!

**Comment by gliubc** [comment]
@SaswatB i like the ability you added, but i am a newbie on electron, and don't know how to build an app from the repo, could you send me an macOS app with the ability you added. My gmail: liubaocheng999@gmail.com . Thank you very much!

**Comment by gabrielperes97** [comment]
It will be merged? These are nice features.

**Comment by 255kb** [comment]
This won't be merged in its current state. 
It was developed in parallel of a big refactoring in which I rewrote most parts of the application. So it should be rebased on master and reworked with the new store system.
Also there are at least 3 topics in this PR and it should be split in 3. 
This was asked on the community chat but never done.

**Comment by gabrielperes97** [comment]
I'm interested to do this. So should I open the issues  for each feature and start developing from the master branch?

**Comment by 255kb** [comment]
@gabrielperes97 Cool :) I think most issues are already open. 

Main idea: 
- Create a new issue OR if already exists ask if someone is already working on it (normally not if not assigned) and propose that you take it so it's clear, then it can be assigned to you.
Currently I am working on swagger import #86 and multiple responses per routes #75, this last one generates big changes. 
- start branch from master
- open PR, add "Closes #xx" In the commit. 
- try to keep your change lightweight (when applicable) so review is easier. Also try to add some spectron tests for your feature (at least the most easy and obvious one)..
- etc
You will find contribution guidelines there: https://github.com/mockoon/mockoon/blob/master/CONTRIBUTING.md

If you have any question you can ask here or on Spectrum https://spectrum.chat/mockoon?tab=posts
Thank you!

**Comment by HeathNaylor** [comment]
Having a problem with this branch.

Steps to duplicate:
- Ensure there is no `node_modules` directory in the root of the project
- Run `npm install`
- Run `npm run serve` to get the following error:
```
npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2019-08-05T20_23_05_526Z-debug.log
```

**Comment by 255kb** [comment]
@HeathNaylor As I explained to @gabrielperes97 this branch is really old, and was done before a huge refactor where many things changed. The npm script `serve` did not exist at that time. 

Also keep in mind that PR may only be accepted if:
- they are based on an issue,
- the contributor asked to work on the issue, and the issue was assigned to him/her
- it contains one and only one fix / feature
- branch originates from most recent master

This branch is kept here as a reference of what was implemented but won't be merge. 
Code should be split. Also @gabrielperes97 already asked to work on the corresponding issues and is assigned to them.

**Pull request closed without merging**
